# Generated by Django 5.0.4 on 2024-11-16 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Torrent',
            new_name='Torrents',
        ),
    ]
