# Generated by Django 5.0.4 on 2024-11-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("torrents", "0002_rename_torrent_torrents"),
    ]

    operations = [
        migrations.CreateModel(
            name="TorrentFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="torrents/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
