# Generated by Django 5.0.4 on 2024-04-24 07:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200, unique=True)),
                ('status', models.TextField(max_length=200, unique=True)),
                ('available', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200, unique=True)),
                ('expiry', models.DateField(default=datetime.date.today)),
                ('imp', models.DateTimeField(default=datetime.datetime.now)),
                ('exp', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200, unique=True)),
                ('dayofbirth', models.DateField(default=datetime.date.today)),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('address', models.TextField(max_length=200, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1)),
                ('certificate', models.TextField(max_length=200, unique=True)),
                ('specialty', models.TextField(max_length=200, unique=True)),
                ('mail', models.EmailField(max_length=200, unique=True)),
                ('position', models.CharField(choices=[('D', 'Doctor'), ('N', 'Nurse'), ('O', 'Other')], default='O', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='dayofbirth',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1),
        ),
        migrations.AddField(
            model_name='patient',
            name='sympton',
            field=models.TextField(default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
