# Generated by Django 5.0.4 on 2024-04-29 05:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_patient_sympton'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(default=datetime.datetime.now)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('completed', models.BooleanField(default=False)),
                ('patientname', models.TextField(max_length=200, unique=True)),
                ('doctorname', models.TextField(max_length=200)),
                ('feestatus', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('start', models.TimeField(default=datetime.datetime.now)),
                ('end', models.TimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
