# Generated by Django 5.0.4 on 2024-05-03 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_appointment_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintainAndRepair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('type', models.CharField(choices=[('M', 'Maintain'), ('R', 'Repair')], default='M', max_length=1)),
                ('detail', models.TextField(max_length=1000)),
            ],
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='sympton',
            new_name='symptom',
        ),
        migrations.AddField(
            model_name='appointment',
            name='rate',
            field=models.CharField(choices=[('E', 'Excellent'), ('G', 'Good'), ('O', 'Ok'), ('P', 'Poor'), ('T', 'Terrible')], default='O', max_length=1),
        ),
        migrations.AddField(
            model_name='device',
            name='description',
            field=models.CharField(choices=[('W', 'Working'), ('M', 'Maintaining'), ('N', 'Normal')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patientname',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='staff',
            name='address',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='staff',
            name='certificate',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='staff',
            name='specialty',
            field=models.TextField(max_length=200),
        ),
    ]
