# Generated by Django 5.0.4 on 2024-05-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_maintainandrepair_rename_sympton_patient_symptom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintainandrepair',
            name='name',
            field=models.TextField(default='', max_length=200),
        ),
    ]
