# Generated by Django 5.0.4 on 2024-05-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_maintainandrepair_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='description',
            field=models.CharField(choices=[('W', 'Working'), ('M', 'Maintaining'), ('N', 'Normal'), ('D', 'Damaged')], default='N', max_length=1),
        ),
    ]
