# Generated by Django 5.0.4 on 2024-05-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_device_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='academicrank',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='staff',
            name='specialtylevel',
            field=models.TextField(default='', max_length=200),
        ),
    ]
