# Generated by Django 5.0.4 on 2024-05-04 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_staff_academicrank_staff_specialtylevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='exp',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='imp',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
