# Generated by Django 5.0.4 on 2024-05-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_medicine_exp_alter_medicine_imp'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='description',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
