# Generated by Django 5.0.4 on 2024-05-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_medicine_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
