# Generated by Django 5.0.4 on 2024-05-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_device_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='mail',
            field=models.EmailField(default='123@gmail.com', max_length=200),
        ),
    ]
