# Generated by Django 5.0.4 on 2024-05-04 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_patient_symptom_appointment_symptom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='symptom',
            new_name='diagnosis',
        ),
    ]
